### ISSUE TITLE
[Support]: Caching not working

### ISSUE THREAD

**Issue by gabaum10** [github/gh-valet#98]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.18.1 (2022-10-20)
gh valet        github/gh-valet v0.1.16
valet-cli       v0.1.0.13965

### What happened?

After migration from circle CI, the caching wasn't migrated quite right.  I attempted to clean it up based on the official actions docs, but it seems that every build is creating its own, new cache.  Even if the hashes are the same.  

![image](https://user-images.githubusercontent.com/1561245/199712835-d5e077c2-244e-4d36-a076-d87bad061e0b.png)

This is what the steps which are installing the deps and setting up the caches look like:

```yml
install_parent_deps:
    name: Install Parent Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Parent Dep Cache
        uses: actions/cache@v3
        with:
          key: npm-parent-${{ hashFiles('package-lock.json') }}
          restore-keys: |-
            npm-parent-${{ hashFiles('package-lock.json') }}
            npm-parent-
          path: node_modules

      - name: Install Parent Dependencies
        run: npm ci

      - name: Save Parent Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-parent-${{ hashFiles('package-lock.json') }}

  install_web_deps:
    name: Install Web Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Web Dep Cache
        uses: actions/cache@v3
        with:
          key: npm-web-${{ hashFiles('veoci-web/package-lock.json') }}
          restore-keys: |-
            npm-web-${{ hashFiles('veoci-web/package-lock.json') }}
            npm-web-
          path: veoci-web/node_modules
      - name: Install Web Dependencies
        run: cd veoci-web && npm ci

      - name: Save Web Cache
        uses: actions/cache@v3
        with:
          path: veoci-web/node_modules
          key: npm-web-${{ hashFiles('veoci-web/package-lock.json') }}
```

Any guidance here would be super helpful.  

Additional info: 
I also attempted to get rid of the manual caching and use the `actions/setup-node@v3` to automatically set it up, but that doesn't seem to work correctly with our monorepo structure, even including a list of package.json files at the parent and each child directory.  

### Relevant log output

```shell
N/A - It's already been migrated, just not 100% correcrly.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabaum10** [comment]
I may have figured this out.  I don't think you need the second "save cache" step as it happens automagically from the first cache step defined.  Can someone just confirm that for me?

**Comment by gabaum10** [comment]
No, that doesn't seem to be workign either.  It seems each branch/PR is generating its own cache for some reason.  Is there not a way to work around that?  

If not, it seems like we will run out of storage space very quickly.

**Comment by gabaum10** [comment]
Yeah, how odd.  On a different branch I'm getting this:

![image](https://user-images.githubusercontent.com/1561245/199732661-da153454-9468-43ce-8153-ece1088f4ad2.png)

Even though there is clearly a cache generated:
![image](https://user-images.githubusercontent.com/1561245/199732863-2ec6aa56-846a-47f7-93cd-c4fdc789a202.png)

And it just saves another one.  What on earth is going on.

**Comment by gabaum10** [comment]
Hmm ok, maybe this is working.  I just triggered it off a branch from master, and it used the cache correctly.

**Comment by gabaum10** [comment]
@luke-engle thanks for the response.  Wait, so does that mean I should include the branch ref in the hash somewhere?  Or the base branch maybe?  That actually sort of makes sense... currently I'm just hashing off the various package-lock files.  

```yml
      - name: Restore Parent Dep Cache
        uses: actions/cache@v2
        with:
          key: npm-parent-${{ hashFiles('package-lock.json') }}
          restore-keys: |-
            npm-parent-${{ hashFiles('package-lock.json') }}
            npm-parent-
          path: node_modules
```
